function
assertThrowsSyntaxError
(
x
)
{
let
success
=
false
;
try
{
eval
(
x
)
;
success
=
true
;
}
catch
(
e
)
{
assert
.
sameValue
(
e
instanceof
SyntaxError
true
)
;
}
assert
.
sameValue
(
success
false
)
;
}
assertThrowsSyntaxError
(
"
class
X
{
x
:
1
}
"
)
if
(
'
assert
.
sameValue
'
in
this
)
{
}
reportCompare
(
0
0
)
;
